# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-22 21:47
from __future__ import unicode_literals

from django.db import migrations
import src.core_auth.models


class Migration(migrations.Migration):

    dependencies = [
        ('core_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', src.core_auth.models.UserManager()),
            ],
        ),
    ]
