# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-06 21:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_auth', '0002_auto_20160922_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='needs_change_password',
            field=models.BooleanField(default=False),
        ),
    ]
